# Makefile for bootstrap_cz
# Last modified 06/07/01

# For GNU gcc
CFLAGS = -O2 -Wall -pedantic

# This one specifies the "cc" C compiler
#CC        = cc $(CFLAGS)
#
# To use "gcc" instead
CC        = gcc $(CFLAGS)


bootstrap_cz: bootstrap_cz.c
	$(CC) -o bootstrap_cz bootstrap_cz.c

